# Generated by Django 5.2.8 on 2025-11-21 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioParqueadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número de espacio')),
                ('tipo', models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto'), ('DISCAPACIDAD', 'Discapacidad')], max_length=20, verbose_name='Tipo de espacio')),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('RESERVADO', 'Reservado'), ('OCUPADO', 'Ocupado'), ('BLOQUEADO', 'Bloqueado')], default='LIBRE', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Espacio de Parqueadero',
                'verbose_name_plural': 'Espacios de Parqueadero',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SIN_RESERVA', 'Vehículo sin reserva'), ('DANIO_ESPACIO', 'Daño en espacio'), ('OCUPACION_INDEBIDA', 'Ocupación indebida'), ('OTRO', 'Otro')], max_length=30, verbose_name='Tipo de incidencia')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del reporte')),
                ('espacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.espacioparqueadero', verbose_name='Espacio relacionado')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de reserva')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('tipo_vehiculo', models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto')], max_length=10, verbose_name='Tipo de vehículo')),
                ('placa', models.CharField(max_length=10, verbose_name='Placa del vehículo')),
                ('estado', models.CharField(choices=[('RESERVADA', 'Reservada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada'), ('VENCIDA', 'Vencida')], default='RESERVADA', max_length=20, verbose_name='Estado')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada real')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de salida real')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.espacioparqueadero', verbose_name='Espacio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
    ]
